// load up the express framework and body-parser helper
// const express = require('express');
import express from 'express';

// const bodyParser = require('body-parser');
// const path = require('path');
import bodyParser from 'body-parser';
import path from 'path';
import JsonDatabase from './api/JsonDatabase';

// create an instance of express to serve our end points
const app = express();

// serve static files generated by Parcel
app.use(express.static('dist'));

// configure express instance with some body-parser settings
// including handling JSON data
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: true }));

app.get('/', (req, res) => {
  res.sendFile(path.join(__dirname, 'index.html'));
})

JsonDatabase('db.json', app);

// const port = process.env.PORT || 80;
const port = () => process.env.PORT;

new Promise((resolve) => {
  const waitingForPort = setInterval(() => {
    if (port()) {
      clearInterval(waitingForPort);
      resolve(port());
    }
  }, 100)
}).then(port => {
  app.listen(port, () => console.log(`Listening on port ${port}`));

})


// let port: any = process.env.PORT;
// if (port == null || port == "") {
//   port = 8000;
// }

// console.log({ port: port(), env: process.env });

// app.listen(port(), () => console.log(`Listening on port ${port()}`));
